name: Build

# Run CI only when a release is created, on changes to main branch, or any PR 
# to main. Do not run CI on any other branch. Also, skip any non-source changes 
# from running on CI
on:
  release:
    types: [created]
  push:
    branches: main
    paths-ignore:
    - 'docs/**'
    - 'examples/**'
    - '.gitignore'
    - 'README.rst'
    - '.github/workflows/manylinux.yml'
    - '.github/workflows/sdl1-sdist.yml'

  pull_request:
    branches: main
    paths-ignore:
    - 'docs/**'
    - 'examples/**'
    - '.gitignore'
    - 'README.rst'
    - '.github/workflows/manylinux.yml'
    - '.github/workflows/sdl1-sdist.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        # windows is covered by appveyor for now
        os: [macos-10.15]
        # os: [windows-latest, macos-10.15]

        # separate versions of cibuildwheel
        cibuildver: ['CIBuildWheel v1', 'CIBuildWheel v2']

        # seperate into matrix for concurrency. 
        # pyver: ['cp27', 'cp35', 'cp36', 'cp37', 'cp38', 'cp39', 'cp310', 'pp27', 'pp36', 'pp37']

        # exclude py2 builds on windows, because they don't work due to the
        # fact that py2 builds use old compiler. There is a workaround for this
        # but is not implemented here because Appveyor can already handle py2
        # on windows
        # exclude:
        #   - os: windows-latest
        #     pyver: 'cp27'
        #   - os: windows-latest
        #     pyver: 'pp27'

    env:
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk"

      CIBW_BEFORE_BUILD: pip install requests numpy
      CIBW_TEST_COMMAND: python -m pygame.tests -v --exclude opengl,timing --time_out 300

      MACDEP_CACHE_PREFIX_PATH: ${{ github.workspace }}/pygame_mac_deps

      # Increase pip debugging output
      CIBW_BUILD_VERBOSITY: 2

    steps:
      - uses: actions/checkout@v2

      - name: Fetch cached Mac deps
        id: macdep-cache
        uses: actions/cache@v2
        with:
          path: $MACDEP_CACHE_PREFIX_PATH
          # The matrix os name (which includes version number) and hash of all files in
          # buildconfig is the key to the cache. If anything changes here, the deps are
          # built again
          key: ${{ matrix.os }}-deps-with-key-${{ hashFiles('buildconfig/**') }}

      - name: Build Mac Deps
        if: runner.os == 'macOS' && steps.macdep-cache.outputs.cache-hit != 'true'
        run: |
          brew install coreutils
          cd buildconfig/macdependencies
          ./install_mac_deps.sh
          cp /usr/local/lib/libportmidi.dylib ${GITHUB_WORKSPACE}/libportmidi.dylib

      # Copy files from cached dir into /usr/local
      # Also copy libportmidi.dylib to where the installed wheel expects it at
      - name: Install Mac deps from cache
        if: runner.os == 'macOS' && steps.macdep-cache.outputs.cache-hit == 'true'
        run: |
          for d in ${MACDEP_CACHE_PREFIX_PATH}/*/; do 
            sudo cp -dR --preserve=mode,ownership $d. /usr/local; 
          done
          cp /usr/local/lib/libportmidi.dylib ${GITHUB_WORKSPACE}/libportmidi.dylib

      # use cibuildwheel v1 to build on older python versions
      - name: Build wheels with CIBuildWheel v1
        # if: matrix.pyver == 'cp27' || matrix.pyver == 'cp35' || matrix.pyver == 'pp27' || matrix.pyver == 'pp36'
        if: matrix.cibuildver == 'CIBuildWheel v1'
        uses: pypa/cibuildwheel@v1.12.0
        env:
          # CIBW_BUILD: ${{ matrix.pyver }}-*
          CIBW_BUILD: cp27-* cp35-* pp27-* pp36-*

      # use latest cibuildwheel for newer python versions
      - name: Build wheels with CIBuildWheel v2
        # if: matrix.pyver != 'cp27' && matrix.pyver != 'cp35' && matrix.pyver != 'pp27' && matrix.pyver != 'pp36'
        if: matrix.cibuildver == 'CIBuildWheel v2'
        uses: pypa/cibuildwheel@v2.1.3
        env:
          # CIBW_BUILD: ${{ matrix.pyver }}-*
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* pp37-*

          # Build universal2 wheels too on an Intel runner.
          # Note that the `arm64` part of the `universal2` wheel cannot be 
          # tested in this configuration.
          # uncomment when arm builds are working
          # CIBW_ARCHS_MACOS: "x86_64 universal2"

      - uses: actions/upload-artifact@v2
        with:
          name: pygame-wheels
          path: ./wheelhouse/*.whl

#   - name: Upload binaries to Github Releases
#     if: github.event_name == 'release'
#     uses: svenstaro/upload-release-action@v2
#     with:
#       repo_token: ${{ secrets.GITHUB_TOKEN }}
#       file: ./wheelhouse/*.whl
#       tag: ${{ github.ref }}
#
#   - name: Upload binaries to PyPI
#     if: github.event_name == 'release'
#     env:
#      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     run: |
#       python3 -m pip install twine
#       twine upload ./wheelhouse/*.whl
